name: CI

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "**/*.md"
      - "**/*.MD"
      - "**/*.ignore"
      - "LICENSE"

  pull_request:
    paths-ignore:
      - "**/*.md"
      - "**/*.MD"
      - "**/*.ignore"
      - "LICENSE"

permissions:
  contents: read

jobs:
  SigGenes:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Check package in Bioconductor Docker
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/SigGenes" \
            -w /SigGenes \
            bioconductor/bioconductor_docker:RELEASE_3_23 \
            Rscript --vanilla -e '
              BiocManager::install(
                c("devtools", "testthat"), ask = FALSE, update = FALSE
              )

              devtools::install_deps(
                dependencies = TRUE, upgrade = "never"
              )

              devtools::document()

              devtools::check(
                error_on = "warning"
              )
            '
